//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public long ActivityLogId { get; set; }
        public string LogType { get; set; }
        public string Description { get; set; }
        public string SearchKeyword { get; set; }
        public string CustID { get; set; }
        public string UserId { get; set; }
        public string ClientIP { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
    }
}
