//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllImage
    {
        public long reference { get; set; }
        public string KeyName { get; set; }
        public string KeyType { get; set; }
        public string Image { get; set; }
        public string ImageHash { get; set; }
    }
}
