//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanySettingForMulti
    {
        public int SettingID { get; set; }
        public string ApiEndPoint { get; set; }
        public string AuthonticationToken { get; set; }
        public string client { get; set; }
        public string company { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    }
}
