//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyProfile
    {
        public int CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyInfo { get; set; }
        public string CompanyVision { get; set; }
        public string CompanyMission { get; set; }
        public string CompanyEmail { get; set; }
        public string CompanyContact1 { get; set; }
        public string CompanyContact2 { get; set; }
        public string CompanyMobile1 { get; set; }
        public string CompanyMobile2 { get; set; }
    }
}
