//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cu_contact
    {
        public string birthday { get; set; }
        public string company_cu { get; set; }
        public string contact { get; set; }
        public string customer { get; set; }
        public string email { get; set; }
        public string fax { get; set; }
        public string job_code { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string phone_ext { get; set; }
        public string titled { get; set; }
        public string image { get; set; }
        public string note { get; set; }
        public string cell { get; set; }
        public string adr { get; set; }
        public string country_code { get; set; }
        public string state { get; set; }
        public string postal_code { get; set; }
        public string web_passwd { get; set; }
        public string web_permissions { get; set; }
        public Nullable<bool> web_parent { get; set; }
        public string date_added { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string prefix { get; set; }
        public string suffix { get; set; }
        public string middle_name { get; set; }
        public string last_update_date { get; set; }
        public string ship_id { get; set; }
        public string marketing_code { get; set; }
        public string mail_type { get; set; }
        public string sy_lookup { get; set; }
        public string last_update { get; set; }
        public Nullable<double> crm_priority { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
