//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cu_prcitem
    {
        public string company_cu { get; set; }
        public string cu_ref { get; set; }
        public string item { get; set; }
        public string cu_item { get; set; }
        public string warehouse { get; set; }
        public string cu_item_desc { get; set; }
        public string price_flag { get; set; }
        public string eff_date { get; set; }
        public string exp_date { get; set; }
        public string C__rowids { get; set; }
        public int C__seq { get; set; }
    }
}
