//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cu_prospect
    {
        public string company_cu { get; set; }
        public string customer { get; set; }
        public string name { get; set; }
        public string country_code { get; set; }
        public string adr { get; set; }
        public string postal_code { get; set; }
        public string phone { get; set; }
        public string phone_ext { get; set; }
        public string fax { get; set; }
        public string salesman1 { get; set; }
        public string salesman2 { get; set; }
        public string salesman3 { get; set; }
        public string primary_contact { get; set; }
        public string web_page { get; set; }
        public string profile { get; set; }
        public string user_code { get; set; }
        public string source_code { get; set; }
        public string Date_created { get; set; }
        public Nullable<decimal> time_created { get; set; }
        public string stat { get; set; }
        public string last_act_date { get; set; }
        public Nullable<decimal> last_act_time { get; set; }
        public string type { get; set; }
        public string state { get; set; }
        public string email_address { get; set; }
        public Nullable<bool> copy_changes { get; set; }
        public string territory { get; set; }
        public string busn_class { get; set; }
        public string price_code { get; set; }
        public Nullable<bool> Active { get; set; }
        public string sy_lookup { get; set; }
        public string terms_code { get; set; }
        public string tax_code { get; set; }
        public Nullable<bool> customer_flag { get; set; }
        public string activity_code { get; set; }
        public Nullable<bool> sales_active_flag { get; set; }
        public Nullable<bool> email_solicitation { get; set; }
        public Nullable<bool> fax_solicitation { get; set; }
        public Nullable<bool> voice_solicitation { get; set; }
        public string sic_code { get; set; }
        public string profile2 { get; set; }
        public string profile3 { get; set; }
        public string parent_customer { get; set; }
        public string best_time { get; set; }
        public Nullable<bool> priority { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
