//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cu_shipto
    {
        public string atn { get; set; }
        public string blnkt_po { get; set; }
        public Nullable<double> com_split2 { get; set; }
        public string company_cu { get; set; }
        public Nullable<double> com_split1 { get; set; }
        public string country_code { get; set; }
        public string cu_tax_class { get; set; }
        public string customer { get; set; }
        public string delivery_route { get; set; }
        public string delivery_terms { get; set; }
        public string fax { get; set; }
        public string freight_zone { get; set; }
        public string name { get; set; }
        public string oe_instr { get; set; }
        public string phone { get; set; }
        public string salesman1 { get; set; }
        public string salesman2 { get; set; }
        public string ship_id { get; set; }
        public string salesman3 { get; set; }
        public string ship_via_code { get; set; }
        public string state { get; set; }
        public Nullable<double> stop { get; set; }
        public string tax_code { get; set; }
        public string tax_exempt { get; set; }
        public string warehouse { get; set; }
        public string postal_code { get; set; }
        public string sy_lookup { get; set; }
        public string image { get; set; }
        public string territory { get; set; }
        public string taxable_flag { get; set; }
        public string adr { get; set; }
        public string phone_ext { get; set; }
        public string ship_via_acct { get; set; }
        public string manifest_adr1 { get; set; }
        public string manifest_adr2 { get; set; }
        public string manifest_adr3 { get; set; }
        public string manifest_adr4 { get; set; }
        public string manifest_adr5 { get; set; }
        public string manifest_adr6 { get; set; }
        public Nullable<bool> residential { get; set; }
        public Nullable<bool> active { get; set; }
        public string dist_ctr { get; set; }
        public string carr_fac_cd { get; set; }
        public string com_class { get; set; }
        public string currency_code { get; set; }
        public string profile { get; set; }
        public Nullable<bool> oe_default { get; set; }
        public string email { get; set; }
        public string web_passwd { get; set; }
        public Nullable<bool> web_show_price { get; set; }
        public string company_oe { get; set; }
        public string cu_group { get; set; }
        public string department { get; set; }
        public string customer_ext { get; set; }
        public string sic_code { get; set; }
        public string delivery_route_wd { get; set; }
        public string stop_wd { get; set; }
        public Nullable<bool> blind_ship { get; set; }
        public string form_quote_dest { get; set; }
        public string form_ackn_dest { get; set; }
        public string form_inv_dest { get; set; }
        public string profile2 { get; set; }
        public string fob { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public string terms_code { get; set; }
        public string profile3 { get; set; }
        public Nullable<bool> vmi_ship_id { get; set; }
        public string last_update { get; set; }
        public Nullable<bool> mail_flag { get; set; }
        public string DOB { get; set; }
        public string mail_type { get; set; }
        public string frt_forwarder { get; set; }
        public string use_cust_tax { get; set; }
        public string cons_to_wh { get; set; }
        public string user_code { get; set; }
        public string DOD { get; set; }
        public string DOR { get; set; }
        public string ssc { get; set; }
        public Nullable<bool> form_ackn_hard_copy { get; set; }
        public Nullable<bool> form_inv_hard_copy { get; set; }
        public Nullable<bool> form_quote_hard_copy { get; set; }
        public string license { get; set; }
        public string license_exp_date { get; set; }
        public string license_recv_date { get; set; }
        public string license_lookup { get; set; }
        public string DOB_date { get; set; }
        public string region { get; set; }
        public string last_sale_date { get; set; }
        public Nullable<double> last_sale_amount { get; set; }
        public string ord_class { get; set; }
        public string price_code { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
