//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cu_taxmst
    {
        public string company_cu { get; set; }
        public string tax_code { get; set; }
        public string descr { get; set; }
        public Nullable<decimal> pct { get; set; }
        public string gl_account { get; set; }
        public string state { get; set; }
        public Nullable<decimal> state_pct { get; set; }
        public string jur_code { get; set; }
        public string jur_pct { get; set; }
        public string jur_gl_account { get; set; }
        public Nullable<bool> no_pc_tax { get; set; }
        public string last_update { get; set; }
        public string C__rowids { get; set; }
        public int C__seq { get; set; }
    }
}
