//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMailTemplate
    {
        public long MailTemplateID { get; set; }
        public string MailTemplateName { get; set; }
        public string MailTemplateSubject { get; set; }
        public string MailTemplateContent { get; set; }
        public bool IsActive { get; set; }
        public string MailType { get; set; }
    }
}
