//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class errorlog
    {
        public int index { get; set; }
        public string errnum { get; set; }
        public string descr { get; set; }
        public string source { get; set; }
        public string sqlstate { get; set; }
        public string nativeerror { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
    }
}
