//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class headerlink
    {
        public int linkid { get; set; }
        public string linkname { get; set; }
        public string linkurl { get; set; }
        public Nullable<int> seq { get; set; }
        public Nullable<bool> popover { get; set; }
        public string types { get; set; }
        public Nullable<int> parent_seq { get; set; }
        public Nullable<int> ismenu { get; set; }
    }
}
