//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class it_compl
    {
        public string comp_item { get; set; }
        public string company_it { get; set; }
        public string item { get; set; }
        public string last_update { get; set; }
        public Nullable<bool> related { get; set; }
        public Nullable<bool> similar { get; set; }
        public Nullable<bool> use_in_poe { get; set; }
        public string warehouse { get; set; }
        public Nullable<bool> use_in_web_grouping { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
