//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class it_component
    {
        public string comp_item { get; set; }
        public Nullable<decimal> comp_qty { get; set; }
        public string company_it { get; set; }
        public string kit_item { get; set; }
        public string um { get; set; }
        public Nullable<bool> variable_item { get; set; }
        public Nullable<bool> vendor_supplied_flag { get; set; }
        public Nullable<decimal> vendor_process_seq { get; set; }
        public Nullable<decimal> bd_priority { get; set; }
        public string last_update { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
