//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class it_majcls
    {
        public string company_it { get; set; }
        public string descr { get; set; }
        public string it_acct_class { get; set; }
        public string it_maj_class { get; set; }
        public string ltl_nmfc { get; set; }
        public string ltl_class { get; set; }
        public string alpha_sort { get; set; }
        public string web_descr { get; set; }
        public string web_image { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
        public string meta_descr { get; set; }
        public string meta { get; set; }
        public string title_tag { get; set; }
    }
}
