//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class it_prodline
    {
        public string meta { get; set; }
        public string title_tag { get; set; }
        public string company_it { get; set; }
        public string descr { get; set; }
        public Nullable<bool> discount_flag { get; set; }
        public Nullable<bool> force_cost { get; set; }
        public string maj_class { get; set; }
        public string tax_class { get; set; }
        public string product_line { get; set; }
        public string cogs { get; set; }
        public string w_cost { get; set; }
        public Nullable<bool> use_item_req { get; set; }
        public string alpha_sort { get; set; }
        public string sa_group_label { get; set; }
        public string ord_class { get; set; }
        public Nullable<decimal> new_item_cost_multiple { get; set; }
        public Nullable<decimal> cost_multiplier { get; set; }
        public Nullable<decimal> rental_depr_pct { get; set; }
        public Nullable<decimal> rental_depr_days { get; set; }
        public Nullable<decimal> rental_list_pct { get; set; }
        public string supplier_class { get; set; }
        public string comm_class { get; set; }
        public Nullable<bool> msds_required { get; set; }
        public string vend_gsc { get; set; }
        public string vend_generic_item { get; set; }
        public string um { get; set; }
        public string profile { get; set; }
        public string web_descr { get; set; }
        public string web_image { get; set; }
        public string sa_group_label_1 { get; set; }
        public string sa_group_label_2 { get; set; }
        public string sa_group_label_3 { get; set; }
        public string sa_group_label_4 { get; set; }
        public string sa_group_label_5 { get; set; }
        public string sa_group_label_6 { get; set; }
        public string sa_group_label_7 { get; set; }
        public string sa_group_label_8 { get; set; }
        public string sa_group_label_9 { get; set; }
        public string sa_group_label_10 { get; set; }
        public string sa_group_label_11 { get; set; }
        public string sa_group_label_12 { get; set; }
        public string sa_group_label_13 { get; set; }
        public string sa_group_label_14 { get; set; }
        public string sa_group_label_15 { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
