//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class it_sales_restriction
    {
        public string company_it { get; set; }
        public string company_oe { get; set; }
        public string item { get; set; }
        public string region { get; set; }
        public string product_line { get; set; }
        public string restriction_type { get; set; }
        public string customer { get; set; }
        public string restriction_flag { get; set; }
        public string ord_class { get; set; }
        public string last_update { get; set; }
        public string eff_date { get; set; }
        public string exp_date { get; set; }
        public string country_code { get; set; }
        public string state { get; set; }
        public string warehouse { get; set; }
        public string C__rowids { get; set; }
        public Nullable<long> C__seq { get; set; }
    }
}
