//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class it_tree_link
    {
        public string company_it { get; set; }
        public string tree_node { get; set; }
        public string item { get; set; }
        public Nullable<decimal> sequence { get; set; }
        public string last_update { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
