//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class it_tree_node
    {
        public string meta { get; set; }
        public string title_tag { get; set; }
        public string company_it { get; set; }
        public string tree_node { get; set; }
        public string name { get; set; }
        public string descr { get; set; }
        public string image { get; set; }
        public Nullable<decimal> sequence { get; set; }
        public string parent_node { get; set; }
        public Nullable<decimal> left_node { get; set; }
        public Nullable<decimal> right_node { get; set; }
        public string last_update { get; set; }
        public Nullable<bool> hidden { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
        public string web_id { get; set; }
        public string meta_descr { get; set; }
    }
}
