//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class it_xref
    {
        public string company_it { get; set; }
        public string item { get; set; }
        public string xref_id { get; set; }
        public string descr { get; set; }
        public string type { get; set; }
        public string vendor { get; set; }
        public Nullable<decimal> vendor_avg_lead_time { get; set; }
        public string last_rcpt_date { get; set; }
        public Nullable<decimal> vendor_purch_mult { get; set; }
        public Nullable<decimal> vendor_price { get; set; }
        public string vendor_price_per { get; set; }
        public string customer { get; set; }
        public string company_cu { get; set; }
        public string company_ve { get; set; }
        public string last_update { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
