//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemdetail
    {
        public long id { get; set; }
        public string item { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public string details_or_url { get; set; }
        public Nullable<int> sequence { get; set; }
        public Nullable<bool> IMType { get; set; }
    }
}
