//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSummery
    {
        public long C__seq { get; set; }
        public string C__rowids { get; set; }
        public Nullable<int> sum_qty { get; set; }
        public string sum_sum_key_1 { get; set; }
        public Nullable<int> sum_sum_year { get; set; }
        public string sum_company_sy { get; set; }
        public string sum_sum_name { get; set; }
    }
}
