//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class oe_class
    {
        public Nullable<bool> ar_flag { get; set; }
        public Nullable<bool> blanket { get; set; }
        public string bo_ord_class { get; set; }
        public string company_oe { get; set; }
        public string descr { get; set; }
        public Nullable<double> demand_pct { get; set; }
        public Nullable<bool> hold_flag { get; set; }
        public Nullable<bool> hit_inventory { get; set; }
        public Nullable<double> load { get; set; }
        public Nullable<double> max_gp { get; set; }
        public Nullable<double> min_gp { get; set; }
        public Nullable<bool> op_flag { get; set; }
        public string ord_class { get; set; }
        public Nullable<double> pct_stock { get; set; }
        public Nullable<bool> prt_ext { get; set; }
        public Nullable<bool> prt_ord_tot { get; set; }
        public Nullable<bool> prt_price { get; set; }
        public Nullable<bool> quote_flag { get; set; }
        public Nullable<bool> rent_flag { get; set; }
        public Nullable<bool> sample_flag { get; set; }
        public Nullable<bool> ship_ord { get; set; }
        public Nullable<bool> transfer_flag { get; set; }
        public string po_ord_class { get; set; }
        public Nullable<bool> print_ni_ps { get; set; }
        public Nullable<bool> oe_totals_flag { get; set; }
        public Nullable<bool> sa_totals_flag { get; set; }
        public Nullable<bool> oe_forms_flag { get; set; }
        public Nullable<bool> print_sample_price { get; set; }
        public Nullable<bool> post_ar_gl { get; set; }
        public string season_start_date { get; set; }
        public string season_end_date { get; set; }
        public Nullable<bool> points_active { get; set; }
        public string from_units { get; set; }
        public string to_units { get; set; }
        public string extra_points { get; set; }
        public Nullable<bool> always_bo { get; set; }
        public Nullable<bool> bill_hold_flag { get; set; }
        public Nullable<bool> hold_bill_flag { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
