//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class oe_totcodes
    {
        public string company_oe { get; set; }
        public string tot_cd { get; set; }
        public string descr { get; set; }
        public string gl_account { get; set; }
        public Nullable<bool> tax_flg { get; set; }
        public Nullable<bool> cash_disc_flg { get; set; }
        public Nullable<bool> hist_flg { get; set; }
        public Nullable<bool> comm_flg { get; set; }
        public Nullable<bool> frt_sc_flg { get; set; }
        public Nullable<bool> cost_from_manifest { get; set; }
        public Nullable<bool> amt_from_manifest { get; set; }
        public Nullable<bool> prop_by_shipment { get; set; }
        public Nullable<bool> every_shipment { get; set; }
        public Nullable<bool> rounding { get; set; }
        public string cu_acct_class { get; set; }
        public Nullable<bool> taxable_by_state { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
