//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordereditem
    {
        public int orderindex { get; set; }
        public string productline { get; set; }
        public string itemnumber { get; set; }
        public string image { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> priceExt { get; set; }
        public string descr { get; set; }
        public string warehouse { get; set; }
        public int line { get; set; }
        public string um_o { get; set; }
        public string note { get; set; }
        public Nullable<int> spoil_line_add { get; set; }
        public Nullable<short> override_price { get; set; }
        public Nullable<short> tax_flag { get; set; }
    }
}
