//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderhead
    {
        public long OrderID { get; set; }
        public Nullable<bool> OrderStatus { get; set; }
        public string response { get; set; }
        public string customer { get; set; }
        public string rec_type { get; set; }
        public string ord_class { get; set; }
        public string warehouse { get; set; }
        public string ship_id { get; set; }
        public string ship_via_code { get; set; }
        public string order_by { get; set; }
        public string terms_code { get; set; }
        public string email { get; set; }
        public string source_code { get; set; }
        public string wanted_date { get; set; }
        public string cu_po { get; set; }
        public string notes { get; set; }
        public Nullable<bool> echo { get; set; }
        public Nullable<bool> complete { get; set; }
        public string orderby_phone { get; set; }
        public string ship_via_acct { get; set; }
        public string bill_phone { get; set; }
        public string bill_fax { get; set; }
        public string bill_adr { get; set; }
        public Nullable<decimal> o_tot_taxable_it { get; set; }
        public Nullable<decimal> o_tot_tax_amt { get; set; }
        public Nullable<decimal> o_tot_net_ar { get; set; }
        public string CardNumber { get; set; }
        public string ExpirationDate { get; set; }
        public string SecurityCode { get; set; }
        public Nullable<int> ExpirationMonth { get; set; }
        public Nullable<int> ExpirationYear { get; set; }
        public string CardType { get; set; }
    }
}
