//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public int orderindex { get; set; }
        public string method { get; set; }
        public string cardtype { get; set; }
        public string ccardnum { get; set; }
        public string cfname { get; set; }
        public string clname { get; set; }
        public string cexdatey { get; set; }
        public string cexdatem { get; set; }
        public string cvv2 { get; set; }
        public string POnum { get; set; }
        public int seq { get; set; }
        public string pay_cd { get; set; }
        public Nullable<decimal> pay_amount { get; set; }
    }
}
