//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class price_sale
    {
        public string company_ip { get; set; }
        public string it_group { get; set; }
        public string item { get; set; }
        public string @base { get; set; }
        public Nullable<double> mult_prc { get; set; }
        public string price_per { get; set; }
        public Nullable<bool> always_use_price { get; set; }
        public Nullable<bool> disc_usual_price { get; set; }
        public Nullable<decimal> cost { get; set; }
        public string cost_per { get; set; }
        public string eff_date { get; set; }
        public string exp_date { get; set; }
        public Nullable<decimal> com_pct { get; set; }
        public string company_it { get; set; }
        public string cu_group { get; set; }
        public string customer { get; set; }
        public string company_cu { get; set; }
        public Nullable<bool> use_sale_price_group { get; set; }
        public string currency_code { get; set; }
        public string col_base_2 { get; set; }
        public string col_label_2 { get; set; }
        public string col_mult_prc_2 { get; set; }
        public string col_qty_brk_2 { get; set; }
        public Nullable<decimal> col_qty_level { get; set; }
        public Nullable<bool> use_qty_breaks { get; set; }
        public string warehouse { get; set; }
        public string ord_class { get; set; }
        public string col_qty_level_2 { get; set; }
        public Nullable<bool> web_only { get; set; }
        public string last_update { get; set; }
        public string reference { get; set; }
        public Nullable<decimal> retail_price { get; set; }
        public Nullable<bool> broken_pack_pricing { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
