//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class price
    {
        public string company_ip { get; set; }
        public string cost_price_flg { get; set; }
        public string it_group { get; set; }
        public string item { get; set; }
        public string cu_group { get; set; }
        public string customer { get; set; }
        public string ve_group { get; set; }
        public string vendor { get; set; }
        public string sched_code { get; set; }
        public string @base { get; set; }
        public string col_mult_prc { get; set; }
        public string col_qty_brk { get; set; }
        public Nullable<decimal> col_qty_level { get; set; }
        public string col_label { get; set; }
        public string fut_mult_prc { get; set; }
        public string fut_qty_brk { get; set; }
        public string fut_label { get; set; }
        public string fut_eff_date { get; set; }
        public string col_man_prc { get; set; }
        public string fut_man_prc { get; set; }
        public string com_pct { get; set; }
        public string fut_com_pct { get; set; }
        public string company_it { get; set; }
        public string company_cu { get; set; }
        public string company_ve { get; set; }
        public string col_base_2 { get; set; }
        public string col_label_2 { get; set; }
        public string col_mult_prc_2 { get; set; }
        public string col_qty_brk_2 { get; set; }
        public string fut_base_2 { get; set; }
        public string fut_label_2 { get; set; }
        public string fut_mult_prc_2 { get; set; }
        public string fut_qty_brk_2 { get; set; }
        public string com_pct_2 { get; set; }
        public string fut_com_pct_2 { get; set; }
        public string currency_code { get; set; }
        public string ord_class { get; set; }
        public string pricing_terms { get; set; }
        public string last_fut_update { get; set; }
        public string warehouse { get; set; }
        public string col_qty_level_2 { get; set; }
        public string last_update { get; set; }
        public Nullable<bool> broken_pack_pricing { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
