//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PunchoutSessionDetail
    {
        public long Id { get; set; }
        public string CustomerId { get; set; }
        public string UserId { get; set; }
        public string ShipTo { get; set; }
        public string DeliverTo { get; set; }
        public string ReturnURL { get; set; }
        public string jsonobject { get; set; }
    }
}
