//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationControl
    {
        public int controlid { get; set; }
        public string controlname { get; set; }
        public string controltype { get; set; }
        public Nullable<bool> isrequired { get; set; }
        public Nullable<bool> isemail { get; set; }
        public string dropdowntype { get; set; }
        public string dropdowndetails { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<int> sequence { get; set; }
        public string DefaultValues { get; set; }
        public Nullable<bool> IsDisabled { get; set; }
    }
}
