//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class salesman
    {
        public string adr1 { get; set; }
        public string adr2 { get; set; }
        public string city { get; set; }
        public Nullable<decimal> com_load_pct { get; set; }
        public Nullable<decimal> com_min_amount { get; set; }
        public Nullable<bool> com_min_flag { get; set; }
        public Nullable<decimal> com_min_gp { get; set; }
        public Nullable<decimal> com_pct { get; set; }
        public Nullable<bool> com_type { get; set; }
        public string company_cu { get; set; }
        public string company_oe { get; set; }
        public string employ_date { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string salesman1 { get; set; }
        public string state { get; set; }
        public string user_id { get; set; }
        public string postal_code { get; set; }
        public string image { get; set; }
        public string fax { get; set; }
        public string email_address { get; set; }
        public string country_code { get; set; }
        public string adr { get; set; }
        public string alt_email_address { get; set; }
        public string web_passwd { get; set; }
        public string territory { get; set; }
        public string sales_group { get; set; }
        public string warehouse { get; set; }
        public Nullable<bool> excl_oa_email_sale { get; set; }
        public Nullable<bool> excl_qu_email_sale { get; set; }
        public string zone { get; set; }
        public Nullable<bool> al_cr_activity { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
