//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipvia_mapping
    {
        public int shipmatchid { get; set; }
        public string shipvia_code { get; set; }
        public string name { get; set; }
        public string provider { get; set; }
        public string providercode { get; set; }
        public Nullable<int> Markup { get; set; }
        public Nullable<int> type { get; set; }
    }
}
