//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ship_rates
    {
        public string ship_via_code { get; set; }
        public string zone { get; set; }
        public int weightMin { get; set; }
        public int weightMax { get; set; }
        public Nullable<decimal> rate { get; set; }
        public string type { get; set; }
    }
}
