//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SouthernPunchOutSession
    {
        public long Id { get; set; }
        public string CustomerId { get; set; }
        public string BuyerCookie { get; set; }
        public string SupplierPartID { get; set; }
        public string DeliverTo { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string ReturnURL { get; set; }
        public string FromId { get; set; }
        public string ToId { get; set; }
        public string SenderId { get; set; }
        public string UserAgent { get; set; }
    }
}
