//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_country
    {
        public string country_descr { get; set; }
        public string country_code { get; set; }
        public string fmt_postal { get; set; }
        public string fmt_address { get; set; }
        public string use_address { get; set; }
        public string fmt_phone { get; set; }
        public string label_address { get; set; }
        public string currency_code { get; set; }
        public string label_postal { get; set; }
        public string fmt_state { get; set; }
        public Nullable<bool> use_state { get; set; }
        public string label_state { get; set; }
        public Nullable<bool> validate_state { get; set; }
        public string region { get; set; }
        public string adr_format { get; set; }
        public Nullable<bool> use_adr_fmt { get; set; }
        public string fmt_faxdial { get; set; }
        public Nullable<decimal> adr_no_city { get; set; }
        public string country_code_iso { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
