//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_company
    {
        public string name { get; set; }
        public string adr { get; set; }
        public string state { get; set; }
        public string postal_code { get; set; }
        public string country_code { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string company_oe { get; set; }
        public string company_sa { get; set; }
        public string company_ar { get; set; }
        public Nullable<decimal> gl_yr { get; set; }
        public string company_cu { get; set; }
        public string company_it { get; set; }
        public string company_ap { get; set; }
        public string company_gl { get; set; }
        public string company_sy { get; set; }
        public string co_wh_dflt { get; set; }
        public Nullable<bool> gl_intf { get; set; }
        public Nullable<decimal> beg_fisc_mo { get; set; }
        public string company_ip { get; set; }
        public string gl_ret_earn { get; set; }
        public string co_email { get; set; }
        public string co_web { get; set; }
        public Nullable<decimal> manuf_id { get; set; }
        public string company_po { get; set; }
        public string company_ve { get; set; }
        public Nullable<decimal> acctg_year { get; set; }
        public Nullable<decimal> acctg_month { get; set; }
        public string SMTPServer { get; set; }
        public string POPUsername { get; set; }
        public string POPPassword { get; set; }
        public Nullable<bool> residential { get; set; }
        public string bank_account { get; set; }
        public string ed_serial { get; set; }
        public Nullable<decimal> SMTPAuth { get; set; }
        public string ein { get; set; }
        public string remitto_name { get; set; }
        public string remitto_adr { get; set; }
        public string remitto_state { get; set; }
        public string remitto_postal_code { get; set; }
        public string remitto_country_code { get; set; }
        public string remitto_phone { get; set; }
        public string remitto_fax { get; set; }
        public Nullable<bool> email_receipt { get; set; }
        public string customer { get; set; }
        public string go_live_date { get; set; }
        public Nullable<bool> gl_post_receipts { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
