//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_currency
    {
        public string company_sy { get; set; }
        public string currency_code { get; set; }
        public string descr { get; set; }
        public Nullable<decimal> exchange_rate { get; set; }
        public Nullable<bool> organization_default { get; set; }
        public string exchange_gl { get; set; }
        public string Last_mod_user_id { get; set; }
        public string Last_mod_date { get; set; }
        public Nullable<decimal> last_mod_time { get; set; }
        public string bank_gl { get; set; }
        public Nullable<bool> bank_in_currency { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
