//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_default
    {
        public string user_id { get; set; }
        public string company_sy { get; set; }
        public string pgm { get; set; }
        public string name_list { get; set; }
        public string value_list { get; set; }
        public string type_list { get; set; }
        public string select_list { get; set; }
        public string name { get; set; }
        public Nullable<bool> default_options { get; set; }
        public string last_used_date { get; set; }
        public string last_used_dt { get; set; }
        public string last_used_by { get; set; }
        public string created_dt { get; set; }
        public string created_by { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
