//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_numctrl
    {
        public string company_sy { get; set; }
        public Nullable<decimal> sequence { get; set; }
        public string type { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
