//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_paycodes
    {
        public Nullable<bool> auth_flag { get; set; }
        public Nullable<bool> card_flag { get; set; }
        public Nullable<bool> cash_flag { get; set; }
        public string company_sy { get; set; }
        public string descr { get; set; }
        public string gl { get; set; }
        public string pay_code { get; set; }
        public Nullable<bool> sec_code_flag { get; set; }
        public Nullable<bool> print_cc_receipt { get; set; }
        public Nullable<decimal> cc_receipt_copies { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
