//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_param
    {
        public string company_sy { get; set; }
        public string par { get; set; }
        public string descr { get; set; }
        public string cat { get; set; }
        public string par_format { get; set; }
        public string par_type { get; set; }
        public string par_value { get; set; }
        public string valid_entries { get; set; }
        public string help_text { get; set; }
        public string date_added { get; set; }
        public string sy_lookup { get; set; }
        public Nullable<decimal> priority { get; set; }
        public string last_update { get; set; }
        public Nullable<bool> sensitive { get; set; }
        public Nullable<bool> allow_user_ovrd { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
