//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_postal_code
    {
        public string country_code { get; set; }
        public string postal_code { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string tax_code { get; set; }
        public string warehouse { get; set; }
        public string territory { get; set; }
        public string last_update { get; set; }
        public string time_zone { get; set; }
        public string delivery_route { get; set; }
        public string from_plus_four { get; set; }
        public string to_plus_four { get; set; }
        public string salesman1 { get; set; }
        public string busn_class { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
