//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_prof_label
    {
        public string company_sy { get; set; }
        public string pgm { get; set; }
        public string prof_label { get; set; }
        public string table_lookup { get; set; }
        public string prof_label2 { get; set; }
        public string table_lookup2 { get; set; }
        public string prof_label3 { get; set; }
        public string table_lookup3 { get; set; }
        public string C__rowids { get; set; }
        public string C__seq { get; set; }
    }
}
