//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_shipvia
    {
        public string ship_via_code { get; set; }
        public string descr { get; set; }
        public string label_code { get; set; }
        public string consignee { get; set; }
        public Nullable<bool> type { get; set; }
        public string carrier { get; set; }
        public string scac_code { get; set; }
        public Nullable<bool> prepaid { get; set; }
        public string service_type { get; set; }
        public string billing_opt { get; set; }
        public string hand_charge_type { get; set; }
        public string return_service_type { get; set; }
        public string pack_type { get; set; }
        public string oversize { get; set; }
        public string flex_parcel_ins_type { get; set; }
        public Nullable<bool> hand_charge_opt { get; set; }
        public Nullable<decimal> hand_charge_flat_rate { get; set; }
        public Nullable<decimal> hand_charge_pct { get; set; }
        public Nullable<bool> return_service_opt { get; set; }
        public Nullable<bool> saturday_deliv_opt { get; set; }
        public Nullable<bool> saturday_pickup_opt { get; set; }
        public Nullable<bool> add_hand_opt { get; set; }
        public Nullable<bool> insured_val_opt { get; set; }
        public Nullable<bool> flex_parcel_ins_opt { get; set; }
        public Nullable<bool> deliv_conf_opt { get; set; }
        public string deliv_conf_type { get; set; }
        public Nullable<bool> haz_material_opt { get; set; }
        public Nullable<bool> verbal_conf_opt { get; set; }
        public string verbal_conf_name { get; set; }
        public string verbal_conf_phone { get; set; }
        public Nullable<decimal> priority_level { get; set; }
        public Nullable<decimal> cc_preauth_mul { get; set; }
        public string zone_code { get; set; }
        public string printer_oe { get; set; }
        public string dhl_local_product_code { get; set; }
        public string dhl_account_no { get; set; }
        public string dhl_default_service { get; set; }
        public string dhl_services_list { get; set; }
        public string dhl_shipper_id { get; set; }
        public Nullable<bool> free_ship { get; set; }
        public Nullable<bool> web { get; set; }
        public string web_descr { get; set; }
        public Nullable<bool> expedite { get; set; }
        public string packing_station { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
