//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_trans_notes
    {
        public string company_sy { get; set; }
        public Nullable<double> trans_no { get; set; }
        public Nullable<double> trans_line { get; set; }
        public Nullable<double> trans_seq { get; set; }
        public string note { get; set; }
        public string print_where { get; set; }
        public Nullable<bool> pop_up { get; set; }
        public string last_mod_date { get; set; }
        public Nullable<double> last_mod_time { get; set; }
        public string enter_by { get; set; }
        public Nullable<double> note_seq { get; set; }
        public string note_type { get; set; }
        public Nullable<double> master_note_seq { get; set; }
        public string master_note_type { get; set; }
        public string table_key { get; set; }
        public string master_company_sy { get; set; }
        public string disp_method { get; set; }
        public string disp_where { get; set; }
        public string enter_date { get; set; }
        public Nullable<double> enter_time { get; set; }
        public string last_mod_user_id { get; set; }
        public string spec_group { get; set; }
        public string spec { get; set; }
        public Nullable<bool> copied_master_note { get; set; }
        public string note_image { get; set; }
        public string spec_answer { get; set; }
        public string spec_question { get; set; }
        public Nullable<bool> html_note { get; set; }
        public Nullable<bool> priority { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
