//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_terms
    {
        public string descr { get; set; }
        public Nullable<decimal> disc_grace { get; set; }
        public Nullable<decimal> dsc_days { get; set; }
        public Nullable<decimal> due_days { get; set; }
        public string nxt_terms_code { get; set; }
        public string due_addm { get; set; }
        public string due_day { get; set; }
        public string due_per_end { get; set; }
        public Nullable<bool> price_op { get; set; }
        public Nullable<decimal> t_dsc_pct { get; set; }
        public string terms_code { get; set; }
        public Nullable<bool> use_in_ship { get; set; }
        public string disc_addm { get; set; }
        public string disc_day { get; set; }
        public string disc_per_end { get; set; }
        public Nullable<bool> cod_opt { get; set; }
        public Nullable<bool> ccheck_mo_only { get; set; }
        public Nullable<bool> add_shipping_to_cod { get; set; }
        public Nullable<bool> tot_qp { get; set; }
        public string due_date { get; set; }
        public string disc_date { get; set; }
        public Nullable<bool> split_billing { get; set; }
        public Nullable<bool> allow_cod_payments { get; set; }
        public Nullable<decimal> split_total_payments { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
