//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sy_url_alias
    {
        public int alias_id { get; set; }
        public string alias_str { get; set; }
        public string record_type { get; set; }
        public string record_key { get; set; }
        public Nullable<int> redirect { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
    }
}
