//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCart
    {
        public long CartId { get; set; }
        public string itemnumber { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string MeasureUnit { get; set; }
        public string Price { get; set; }
        public string UserId { get; set; }
        public string SessionId { get; set; }
        public string PricePer { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
