//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        public long OrderId { get; set; }
        public string company_oe { get; set; }
        public string order_ext { get; set; }
        public string notes { get; set; }
        public string ship_via_acct { get; set; }
        public string wanted_date { get; set; }
        public string customer { get; set; }
        public string warehouse { get; set; }
        public string s_adr1 { get; set; }
        public string s_adr2 { get; set; }
        public string s_adr3 { get; set; }
        public string s_adr4 { get; set; }
        public string s_adr5 { get; set; }
        public string s_adr6 { get; set; }
        public string stat { get; set; }
        public string rec_type { get; set; }
        public string ship_id { get; set; }
        public string auth_amount { get; set; }
        public string source_code { get; set; }
        public string pay_amount { get; set; }
        public string tot_code { get; set; }
        public string tot_code_amt { get; set; }
        public string pay_code { get; set; }
        public string pay_cd { get; set; }
        public string pay_code_ref { get; set; }
        public string pay_code_amount { get; set; }
        public string pay_code_card { get; set; }
        public string pay_code_exp { get; set; }
        public string pay_code_sec_code { get; set; }
        public string pay_code_card_length { get; set; }
        public string blind_ship { get; set; }
        public string tax_amount { get; set; }
        public string disp_where { get; set; }
        public string disp_method { get; set; }
        public string print_where { get; set; }
        public string s_st { get; set; }
        public string s_postal_code { get; set; }
        public string s_country_code { get; set; }
        public string tax_code { get; set; }
        public string s_name { get; set; }
        public string order_by { get; set; }
        public string cu_po { get; set; }
        public string email_address { get; set; }
        public string s_phone { get; set; }
        public string ship_atn { get; set; }
        public string company_cu { get; set; }
        public string ord_class { get; set; }
        public string s_phone_ext { get; set; }
        public string ship_via_code { get; set; }
        public string terms_code { get; set; }
        public string salesman1 { get; set; }
        public string disc_amount { get; set; }
        public string Cred_card { get; set; }
        public string Cred_card_exp { get; set; }
        public string Cred_card_type { get; set; }
        public string Auth_type { get; set; }
        public string Auth_asv { get; set; }
        public string Auth_date { get; set; }
        public string Auth_time { get; set; }
        public string Auth_memo { get; set; }
        public string Auth_number { get; set; }
        public string Auth_trans_number { get; set; }
        public string atn { get; set; }
        public string ttable { get; set; }
        public string triggers { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
    }
}
