//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ve_contact
    {
        public string birthday { get; set; }
        public string titled { get; set; }
        public string company_ve { get; set; }
        public string email { get; set; }
        public string fax { get; set; }
        public string job_code { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string phone_ext { get; set; }
        public string vendor { get; set; }
        public string note { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
