//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vendor
    {
        public string company_ve { get; set; }
        public string vendor1 { get; set; }
        public string fax { get; set; }
        public string deliv_terms { get; set; }
        public string sy_lookup { get; set; }
        public string gl { get; set; }
        public string addl_gl { get; set; }
        public string ve_acct_class { get; set; }
        public string name { get; set; }
        public string state { get; set; }
        public string postal_code { get; set; }
        public string phone { get; set; }
        public string fob { get; set; }
        public string ord_class { get; set; }
        public string ve_group { get; set; }
        public Nullable<double> last_po_amount { get; set; }
        public string last_po_date { get; set; }
        public Nullable<double> last_ap_amount { get; set; }
        public string last_ap_date { get; set; }
        public Nullable<double> last_pay_amount { get; set; }
        public string last_pay_date { get; set; }
        public string terms_code { get; set; }
        public Nullable<bool> ten99_flag { get; set; }
        public string atn { get; set; }
        public string profile { get; set; }
        public Nullable<double> addl_disc { get; set; }
        public string addl_disc_gl { get; set; }
        public Nullable<double> safety_pct { get; set; }
        public Nullable<double> review_days { get; set; }
        public Nullable<double> review_days_s { get; set; }
        public Nullable<double> season_adj { get; set; }
        public Nullable<double> dflt_ldtm_days { get; set; }
        public Nullable<bool> dflt_ldtm_flag { get; set; }
        public string ln_type { get; set; }
        public Nullable<double> ln_amount { get; set; }
        public string buy_type { get; set; }
        public string ship_via_code { get; set; }
        public Nullable<bool> po_req { get; set; }
        public string buyer_code { get; set; }
        public string our_customer { get; set; }
        public string add_code { get; set; }
        public string add_fact { get; set; }
        public string buying_group { get; set; }
        public string buy_group_pct { get; set; }
        public string fed_tax_id { get; set; }
        public Nullable<double> avg_pay_days { get; set; }
        public string ap_vendor { get; set; }
        public string broker_fax { get; set; }
        public string broker_phone { get; set; }
        public string user_code { get; set; }
        public string source_code { get; set; }
        public string phone_ext { get; set; }
        public string broker_ext { get; set; }
        public string currency_code { get; set; }
        public Nullable<double> item_descr_line { get; set; }
        public string email_address { get; set; }
        public string web_page { get; set; }
        public string label_code { get; set; }
        public Nullable<bool> allow_po { get; set; }
        public string broker { get; set; }
        public string broker_email { get; set; }
        public string po_atn_email { get; set; }
        public Nullable<bool> edi_vend { get; set; }
        public Nullable<double> purch_min { get; set; }
        public Nullable<double> manuf_id { get; set; }
        public Nullable<bool> web { get; set; }
        public Nullable<double> review_b4_rel { get; set; }
        public string adr { get; set; }
        public string country_code { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<bool> residential { get; set; }
        public Nullable<bool> stat { get; set; }
        public Nullable<bool> bo_flag { get; set; }
        public string ship_via_acct { get; set; }
        public string bank_account { get; set; }
        public string ve_tax_code { get; set; }
        public string web_passwd { get; set; }
        public string form_po_dest { get; set; }
        public Nullable<bool> it_transit_flag { get; set; }
        public Nullable<double> ten99_income_code { get; set; }
        public string bank_routing { get; set; }
        public string bank_name { get; set; }
        public Nullable<bool> bank_transfer { get; set; }
        public string bank_type { get; set; }
        public Nullable<bool> ach_process { get; set; }
        public string ach_email { get; set; }
        public string ach_attention { get; set; }
        public Nullable<bool> ach_preauth { get; set; }
        public string ach_id { get; set; }
        public string warehouse { get; set; }
        public string ach_stat { get; set; }
        public string form_file_po { get; set; }
        public string gl_ap { get; set; }
        public string handling_base { get; set; }
        public string storage_base { get; set; }
        public Nullable<double> handling_charge { get; set; }
        public Nullable<double> storage_charge { get; set; }
        public Nullable<double> storage_min_item { get; set; }
        public Nullable<double> storage_min_inv { get; set; }
        public Nullable<double> storage_min_recv { get; set; }
        public string profile2 { get; set; }
        public string profile3 { get; set; }
        public string last_update { get; set; }
        public string ve_restrict_group { get; set; }
        public Nullable<bool> hold_vouchers { get; set; }
        public Nullable<bool> restricted { get; set; }
        public Nullable<double> cash_disc_pct { get; set; }
        public string license { get; set; }
        public string license_exp_date { get; set; }
        public string license_recv_date { get; set; }
        public string license_lookup { get; set; }
        public string bank_institution { get; set; }
        public string tot_payments { get; set; }
        public string tot_days_to_pay { get; set; }
        public string pickup_route { get; set; }
        public Nullable<double> stop { get; set; }
        public string pickup_route_wd { get; set; }
        public string stop_wd { get; set; }
        public string freight_zone { get; set; }
        public Nullable<double> cancel_days { get; set; }
        public string gl_exp { get; set; }
        public string gl_exp_pct { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
