//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wa_item
    {
        public string wa_item_warehouse { get; set; }
        public string wa_item_item { get; set; }
        public Nullable<decimal> wa_item_list_price { get; set; }
        public string wa_item_list_price_per { get; set; }
        public string wa_item_um_alwd { get; set; }
        public Nullable<decimal> wa_item_qty_cmtd { get; set; }
        public Nullable<decimal> wa_item_qty_oh { get; set; }
        public Nullable<decimal> wa_item_purch_min_qty { get; set; }
        public Nullable<decimal> wa_item_max { get; set; }
        public Nullable<decimal> wa_item_purchasing_mult { get; set; }
        public string wa_item_web_um_display { get; set; }
        public Nullable<int> wa_item_web_min { get; set; }
        public Nullable<int> wa_item_web_max { get; set; }
        public Nullable<int> wa_item_web_mult { get; set; }
        public string wa_item_web_um_alwd { get; set; }
        public Nullable<bool> wa_item_drop_ship { get; set; }
        public string retail_price { get; set; }
        public string item_company_it { get; set; }
        public Nullable<decimal> avg_lead_time { get; set; }
        public Nullable<int> qty_transfer_req_in { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
