//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse
    {
        public string ack_prntr { get; set; }
        public Nullable<bool> ack_prntr_auto { get; set; }
        public string atn { get; set; }
        public string company_it { get; set; }
        public string def_loc { get; set; }
        public Nullable<bool> def_loc_flag { get; set; }
        public string po_prntr { get; set; }
        public Nullable<bool> po_prntr_auto { get; set; }
        public string it_ship_prntr { get; set; }
        public Nullable<bool> it_ship_prntr_auto { get; set; }
        public Nullable<bool> Laptop { get; set; }
        public string lb_prntr { get; set; }
        public Nullable<bool> lb_prntr_auto { get; set; }
        public Nullable<bool> loc_flag { get; set; }
        public string name { get; set; }
        public string o_prntr { get; set; }
        public Nullable<bool> o_prntr_auto { get; set; }
        public string org { get; set; }
        public string phone { get; set; }
        public string pt_prntr { get; set; }
        public Nullable<bool> pt_prntr_auto { get; set; }
        public string qt_prntr { get; set; }
        public Nullable<bool> qt_prntr_auto { get; set; }
        public string ship_loc { get; set; }
        public Nullable<bool> ship_loc_flag { get; set; }
        public string state { get; set; }
        public string warehouse1 { get; set; }
        public string wo_prntr { get; set; }
        public Nullable<bool> wo_prntr_auto { get; set; }
        public string postal_code { get; set; }
        public string fax { get; set; }
        public string image { get; set; }
        public string adr { get; set; }
        public string country_code { get; set; }
        public string it_acct_class { get; set; }
        public Nullable<bool> residential { get; set; }
        public string it_req_prntr { get; set; }
        public Nullable<bool> it_req_prntr_auto { get; set; }
        public string it_aprv_prntr { get; set; }
        public string it_recv_prntr { get; set; }
        public Nullable<bool> it_aprv_prntr_auto { get; set; }
        public Nullable<bool> it_recv_prntr_auto { get; set; }
        public string inventory_gl { get; set; }
        public string export_key { get; set; }
        public string customer { get; set; }
        public Nullable<bool> consignment_wh { get; set; }
        public string email_address { get; set; }
        public Nullable<bool> in_transit_wh { get; set; }
        public Nullable<bool> sp_warehouse_flag { get; set; }
        public string sp_vendor { get; set; }
        public Nullable<bool> allow_neg_avail { get; set; }
        public string c_tot_code { get; set; }
        public string user_code { get; set; }
        public string buyer_code { get; set; }
        public string price_customer { get; set; }
        public string ci_prntr { get; set; }
        public Nullable<bool> ci_prntr_auto { get; set; }
        public string cs_prntr { get; set; }
        public Nullable<bool> cs_prntr_auto { get; set; }
        public string ro_prntr { get; set; }
        public Nullable<bool> ro_prntr_auto { get; set; }
        public string note { get; set; }
        public string form_file_xfer { get; set; }
        public string lot_alloc_date { get; set; }
        public string ship_via_acct { get; set; }
        public string C__rowids { get; set; }
        public long C__seq { get; set; }
    }
}
