//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.ClientModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class wishlistheader
    {
        public long WishlistID { get; set; }
        public string WishlistName { get; set; }
        public string username { get; set; }
        public string shipto { get; set; }
        public Nullable<int> type { get; set; }
    }
}
