//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrail
    {
        public long AuditTrailID { get; set; }
        public long RecordID { get; set; }
        public long UserID { get; set; }
        public int ActionType { get; set; }
        public System.DateTime ActionDate { get; set; }
        public Nullable<int> RecordType { get; set; }
    
        public virtual AuditTrailMaster AuditTrailMaster { get; set; }
        public virtual User User { get; set; }
    }
}
