//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public long ErrorLogID { get; set; }
        public System.DateTime ErrorLogTimestamp { get; set; }
        public long UserID { get; set; }
        public string UserName { get; set; }
        public string ErrorType { get; set; }
        public string ErrorMessage { get; set; }
        public string Module { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<int> IsError { get; set; }
    }
}
