//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailQueue
    {
        public long MailQueueID { get; set; }
        public string MailRecipient { get; set; }
        public string MailSubject { get; set; }
        public string MailMessage { get; set; }
        public Nullable<System.DateTime> MailSendDate { get; set; }
        public long MailBoxID { get; set; }
        public bool IsProccessed { get; set; }
        public bool IsDelivered { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ProccessedOn { get; set; }
        public Nullable<System.DateTime> SentOn { get; set; }
        public string ReplyTo { get; set; }
    
        public virtual MailBox MailBox { get; set; }
    }
}
