//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RightRoleMapping
    {
        public long RightID { get; set; }
        public long RoleID { get; set; }
        public string LohaLive { get; set; }
    
        public virtual Right Right { get; set; }
        public virtual RightRoleMapping RightRoleMapping1 { get; set; }
        public virtual RightRoleMapping RightRoleMapping2 { get; set; }
        public virtual Role Role { get; set; }
    }
}
