//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Right
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Right()
        {
            this.RightRoleMappings = new HashSet<RightRoleMapping>();
        }
    
        public long RightID { get; set; }
        public string RightName { get; set; }
        public long RightGroupID { get; set; }
        public string RightURL { get; set; }
        public bool IsActive { get; set; }
        public bool IsVisible { get; set; }
        public Nullable<byte> ApplicableTo { get; set; }
    
        public virtual RightGroup RightGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RightRoleMapping> RightRoleMappings { get; set; }
    }
}
