//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchedulerConfig
    {
        public int SchedulerConfigId { get; set; }
        public string SchedulerName { get; set; }
        public string SchedulerTime { get; set; }
        public string SchedulerTables { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
