//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingMaster
    {
        public long SettingID { get; set; }
        public string SettingName { get; set; }
        public string SettingDatatypeName { get; set; }
        public string SystemDefault { get; set; }
    }
}
