//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserVisit
    {
        public long UserVisitID { get; set; }
        public string UniqueID { get; set; }
        public string UrlName { get; set; }
        public long MemRefNo { get; set; }
        public string IpAddress { get; set; }
        public string Browser { get; set; }
        public System.DateTime VisitTime { get; set; }
    }
}
