//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.AuditTrails = new HashSet<AuditTrail>();
            this.UserMailBoxes = new HashSet<UserMailBox>();
            this.UserProcessTimes = new HashSet<UserProcessTime>();
            this.UserProjectMappings = new HashSet<UserProjectMapping>();
            this.UserRoles = new HashSet<UserRole>();
            this.UserSessions = new HashSet<UserSession>();
            this.VendorUserLoginDetails = new HashSet<VendorUserLoginDetail>();
        }
    
        public long UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public decimal Mobile { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public bool IsLocked { get; set; }
        public bool IsPasswordReset { get; set; }
        public int FailedAttemptCount { get; set; }
        public Nullable<System.DateTime> LockedOn { get; set; }
        public Nullable<System.DateTime> LastLoggedOn { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public long LastUpdatedBy { get; set; }
        public Nullable<decimal> GUIDCode { get; set; }
        public Nullable<System.Guid> AuthenticationToken { get; set; }
        public Nullable<System.DateTime> TokenExpirsOn { get; set; }
        public string MemberRefNo { get; set; }
        public Nullable<bool> IsRemember { get; set; }
        public Nullable<byte> SessionCount { get; set; }
        public string HostName { get; set; }
        public string ApiUserName { get; set; }
        public string ApiPwd { get; set; }
        public string CompanyID { get; set; }
        public string NotificationEmails { get; set; }
        public string ApiEndPoint { get; set; }
        public string ApiToken { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditTrail> AuditTrails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserMailBox> UserMailBoxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProcessTime> UserProcessTimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProjectMapping> UserProjectMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRole> UserRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserSession> UserSessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorUserLoginDetail> VendorUserLoginDetails { get; set; }
    }
}
