//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public long UserLogID { get; set; }
        public System.DateTime UserLogTimestamp { get; set; }
        public long UserID { get; set; }
        public string UserAction { get; set; }
        public string UserActionDescription { get; set; }
        public string IPAddress { get; set; }
        public string Browser { get; set; }
        public string OperatingSystem { get; set; }
        public string ScreenResolution { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<bool> isSuccessful { get; set; }
    }
}
