//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMailBox
    {
        public long MailBoxID { get; set; }
        public string MailBoxName { get; set; }
        public string SMTPServer { get; set; }
        public int SMTPPort { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool IsSSL { get; set; }
        public string MailFrom { get; set; }
        public string ReplyTo { get; set; }
        public bool IsActive { get; set; }
        public long UserID { get; set; }
        public string DisplayName { get; set; }
        public string Company { get; set; }
    
        public virtual User User { get; set; }
    }
}
