//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D1WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorUserLoginDetail
    {
        public long UserSubUserID { get; set; }
        public long UserID { get; set; }
        public string CompanyID { get; set; }
        public string vendor { get; set; }
        public string web_passwd { get; set; }
        public string C__rowids { get; set; }
        public string C__seq { get; set; }
    
        public virtual User User { get; set; }
    }
}
